# Generated by Django 6.0.1 on 2026-02-03 03:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('ORG_ADMIN', 'Organization Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=20)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.organization')),
            ],
            options={
                'db_table': 'organization_invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='organizatio_token_779f11_idx'), models.Index(fields=['email'], name='organizatio_email_a6c4d7_idx')],
            },
        ),
    ]
