# Generated by Django 6.0.1 on 2026-03-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='profile_picture',
            field=models.CharField(blank=True, help_text="Storage path for the organization's profile picture", max_length=512, null=True),
        ),
    ]
