# Generated by Django 6.0.1 on 2026-02-03 04:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_add_organization_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line1', models.CharField(help_text='Street address line 1', max_length=255)),
                ('line2', models.CharField(blank=True, help_text='Street address line 2 (optional)', max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('province_state', models.CharField(help_text='Province, state, or region', max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'addresses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['city', 'country'], name='addresses_city_2f0ed5_idx'), models.Index(fields=['country', 'province_state'], name='addresses_country_d585e4_idx')],
            },
        ),
    ]
