# Generated by Django 6.0.1 on 2026-02-03 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Physical address of the organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='organizations.address'),
        ),
    ]
