# Generated by Django 6.0.1 on 2026-04-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft-delete timestamp; non-null means the organization has been deleted', null=True),
        ),
    ]
