# Generated by Django 6.0.1 on 2026-02-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_alter_organizationmembership_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
