# Generated by Django 6.0.1 on 2026-02-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the organization', null=True),
        ),
    ]
