// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8000/' | (string & {});
};

export type ApplicantAddress = {
    /**
     * Line1
     */
    line1: string;
    /**
     * Line2
     */
    line2?: string | null;
    /**
     * City
     */
    city: string;
    /**
     * Province state
     */
    province_state: string;
    /**
     * Postal code
     */
    postal_code: string;
    /**
     * Country
     *
     * ISO 3166-1 alpha-2 country code
     */
    country: string;
};

export type QuestionAnswer = {
    /**
     * Question
     *
     * Question being answered
     */
    question: string;
    /**
     * Answer text
     *
     * Answer text for text-type questions
     */
    answer_text?: string | null;
    /**
     * Selected choices for MCQ questions (array of strings)
     */
    selected_choices?: Array<string>;
};

export type JobApplicationCreate = {
    /**
     * Job profile
     *
     * Job profile this application is for
     */
    job_profile: string;
    /**
     * First name
     */
    first_name: string;
    /**
     * Last name
     */
    last_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Phone
     */
    phone: string;
    address: ApplicantAddress;
    answers?: Array<QuestionAnswer>;
    /**
     * Resume id
     *
     * File ID returned by the resume upload endpoint (POST /api/applications/submit/upload/resume/)
     */
    resume_id?: string;
};

export type ApplicationAttachment = {
    /**
     * File url
     */
    readonly file_url?: string;
    /**
     * File name
     *
     * Original filename
     */
    file_name: string;
    /**
     * File type
     */
    file_type?: 'resume' | 'cover_letter' | 'portfolio' | 'certificate' | 'other';
    /**
     * File size
     *
     * File size in bytes
     */
    readonly file_size?: number;
    /**
     * Uploaded at
     */
    readonly uploaded_at?: string;
};

export type JobApplicationDetail = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Job profile
     *
     * Job profile this application is for
     */
    job_profile: string;
    /**
     * Job profile title
     */
    readonly job_profile_title?: string;
    /**
     * First name
     */
    first_name: string;
    /**
     * Last name
     */
    last_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Phone
     */
    phone: string;
    /**
     * Status
     */
    status?: 'to_be_reviewed' | 'reviewed' | 'shortlisted' | 'rejected';
    address?: ApplicantAddress;
    /**
     * Answers
     */
    readonly answers?: string;
    readonly attachments?: Array<ApplicationAttachment>;
    /**
     * Submitted at
     */
    readonly submitted_at?: string;
    /**
     * Created at
     */
    readonly created_at?: string;
    /**
     * Updated at
     */
    readonly updated_at?: string;
};

export type ApplicationAnalysis = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Job application
     *
     * The job application being analysed
     */
    readonly job_application?: string;
    /**
     * Status
     */
    status?: 'uploaded' | 'ocr_pending' | 'ocr_done' | 'ai_pending' | 'done' | 'failed';
    /**
     * Error message
     *
     * Error details when status is FAILED
     */
    readonly error_message?: string;
    /**
     * Extracted resume text
     *
     * Full text extracted from the resume PDF via doctr
     */
    readonly extracted_resume_text?: string;
    /**
     * Ai analysis summary
     *
     * High-level summary from AI
     */
    readonly ai_analysis_summary?: string;
    /**
     * Notable traits
     *
     * Array of notable trait strings
     */
    readonly notable_traits?: {
        [key: string]: unknown;
    };
    /**
     * Key skills
     *
     * Array of key skill strings
     */
    readonly key_skills?: {
        [key: string]: unknown;
    };
    /**
     * Score category
     */
    readonly score_category?: {
        [key: string]: unknown;
    } | null;
    /**
     * Detailed analysis
     *
     * Structured object: strengths, areas_for_development, experience[], education[], certifications[]
     */
    readonly detailed_analysis?: {
        [key: string]: unknown;
    } | null;
    /**
     * Created at
     */
    readonly created_at?: string;
    /**
     * Updated at
     */
    readonly updated_at?: string;
};

export type InvitationAccept = {
    /**
     * Token
     */
    token: string;
};

export type InvitationValidate = {
    /**
     * Token
     */
    token: string;
};

export type QualificationWrite = {
    /**
     * Id
     */
    id?: string;
    /**
     * Category
     */
    category: 'skill' | 'experience' | 'education' | 'certification' | 'tool' | 'language' | 'other';
    /**
     * Name
     */
    name: string;
    /**
     * Requirement level
     */
    requirement_level?: 'required' | 'preferred';
    /**
     * Years required
     */
    years_required?: number | null;
    /**
     * Proficiency level
     */
    proficiency_level?: 'beginner' | 'intermediate' | 'advanced' | 'expert';
    /**
     * Order
     */
    order?: number;
};

export type Question = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Text
     *
     * Question text
     */
    text: string;
    /**
     * Question type
     */
    question_type?: 'text' | 'mcq' | 'mcq_single';
    /**
     * Order
     *
     * Display order of the question
     */
    order?: number;
    /**
     * Array of choice strings for multiple choice questions
     */
    choices?: Array<string>;
    /**
     * Is required
     *
     * Whether this question must be answered
     */
    is_required?: boolean;
};

export type JobProfileCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Organization
     *
     * Organization that owns this job profile
     */
    readonly organization?: string;
    /**
     * Category
     *
     * Job category
     */
    category: string;
    /**
     * Employment type
     */
    employment_type?: 'full_time' | 'part_time' | 'contract' | 'internship' | 'freelance' | 'not_applicable';
    /**
     * Experience level
     *
     * Required experience level
     */
    experience_level: string;
    /**
     * Description
     *
     * Detailed job description
     */
    description: string;
    qualifications?: Array<QualificationWrite>;
    questions?: Array<Question>;
};

export type Address = {
    /**
     * Line1
     *
     * Street address line 1
     */
    line1: string;
    /**
     * Line2
     *
     * Street address line 2 (optional)
     */
    line2?: string;
    /**
     * City
     */
    city: string;
    /**
     * Province state
     *
     * Province, state, or region
     */
    province_state: string;
    /**
     * Postal code
     */
    postal_code: string;
    /**
     * Country
     *
     * ISO 3166-1 alpha-2 country code
     */
    country: string;
    /**
     * Created at
     */
    readonly created_at?: string;
    /**
     * Updated at
     */
    readonly updated_at?: string;
};

export type Organization = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     *
     * Description of the organization
     */
    description?: string | null;
    address?: Address;
    /**
     * Status
     */
    status?: 'PENDING' | 'APPROVED' | 'REJECTED' | 'SUSPENDED';
    /**
     * Created at
     */
    readonly created_at?: string;
    /**
     * Approved at
     */
    readonly approved_at?: string | null;
    /**
     * Approved by email
     */
    readonly approved_by_email?: string;
    /**
     * Member count
     */
    readonly member_count?: number;
    /**
     * Can invite
     */
    readonly can_invite?: boolean;
    /**
     * Profile picture url
     */
    readonly profile_picture_url?: string;
};

export type User = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Email
     */
    email: string;
    /**
     * Username
     *
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    /**
     * First name
     */
    first_name: string;
    /**
     * Last name
     */
    last_name: string;
    /**
     * Password
     */
    password: string;
    /**
     * Password confirm
     */
    password_confirm: string;
    /**
     * Invitation token
     */
    invitation_token?: string;
    /**
     * Date joined
     */
    readonly date_joined?: string;
};

export type JobCategory = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Title
     */
    readonly title?: string;
};

export type ExperienceLevel = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Title
     */
    readonly title?: string;
};

export type Qualification = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Category
     */
    category: 'skill' | 'experience' | 'education' | 'certification' | 'tool' | 'language' | 'other';
    /**
     * Name
     */
    name: string;
    /**
     * Requirement level
     */
    requirement_level?: 'required' | 'preferred';
    /**
     * Years required
     */
    years_required?: number | null;
    /**
     * Proficiency level
     */
    proficiency_level?: 'beginner' | 'intermediate' | 'advanced' | 'expert';
    /**
     * Order
     */
    order?: number;
};

export type JobProfileDetail = {
    /**
     * Id
     */
    readonly id?: string;
    organization?: Organization;
    created_by?: User;
    /**
     * Title
     */
    title: string;
    category?: JobCategory;
    /**
     * Employment type
     */
    employment_type?: 'full_time' | 'part_time' | 'contract' | 'internship' | 'freelance' | 'not_applicable';
    experience_level?: ExperienceLevel;
    /**
     * Description
     *
     * Detailed job description
     */
    description: string;
    readonly qualifications?: Array<Qualification>;
    readonly questions?: Array<Question>;
    /**
     * Is active
     *
     * Whether the job profile is active
     */
    is_active?: boolean;
    /**
     * Created at
     */
    readonly created_at?: string;
    /**
     * Updated at
     */
    readonly updated_at?: string;
};

export type OrganizationList = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     *
     * Description of the organization
     */
    description?: string | null;
    address?: Address;
    /**
     * Status
     */
    status?: 'PENDING' | 'APPROVED' | 'REJECTED' | 'SUSPENDED';
    /**
     * Created at
     */
    readonly created_at?: string;
    /**
     * Member count
     */
    readonly member_count?: number;
    /**
     * Profile picture url
     */
    readonly profile_picture_url?: string;
};

export type OrganizationCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     *
     * Description of the organization
     */
    description?: string | null;
    address?: Address;
};

export type InvitationCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Role
     */
    role?: 'ORG_ADMIN' | 'MEMBER';
};

export type OrganizationInvitation = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Organization
     */
    organization: string;
    /**
     * Organization name
     */
    readonly organization_name?: string;
    /**
     * Email
     */
    email: string;
    /**
     * Role
     */
    role?: 'ORG_ADMIN' | 'MEMBER';
    /**
     * Invited by email
     */
    readonly invited_by_email?: string;
    /**
     * Accepted at
     */
    readonly accepted_at?: string | null;
    /**
     * Expires at
     */
    readonly expires_at?: string;
    /**
     * Created at
     */
    readonly created_at?: string;
    /**
     * Is valid
     */
    readonly is_valid?: boolean;
    /**
     * Is expired
     */
    readonly is_expired?: boolean;
};

export type JobProfileList = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Title
     */
    title: string;
    /**
     * Organization
     *
     * Organization that owns this job profile
     */
    organization: string;
    /**
     * Organization name
     */
    readonly organization_name?: string;
    /**
     * Category
     *
     * Job category
     */
    category: string;
    /**
     * Category name
     */
    readonly category_name?: string;
    /**
     * Employment type
     */
    employment_type?: 'full_time' | 'part_time' | 'contract' | 'internship' | 'freelance' | 'not_applicable';
    /**
     * Experience level
     *
     * Required experience level
     */
    experience_level: string;
    /**
     * Experience level name
     */
    readonly experience_level_name?: string;
    /**
     * Created by
     *
     * User who created this job profile
     */
    created_by: string;
    /**
     * Created by email
     */
    readonly created_by_email?: string;
    /**
     * Is active
     *
     * Whether the job profile is active
     */
    is_active?: boolean;
    /**
     * Created at
     */
    readonly created_at?: string;
};

export type JobApplicationDetailWithAnalysis = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Job profile
     *
     * Job profile this application is for
     */
    job_profile: string;
    /**
     * Job profile title
     */
    readonly job_profile_title?: string;
    /**
     * First name
     */
    first_name: string;
    /**
     * Last name
     */
    last_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Phone
     */
    phone: string;
    /**
     * Status
     */
    status?: 'to_be_reviewed' | 'reviewed' | 'shortlisted' | 'rejected';
    address?: ApplicantAddress;
    /**
     * Answers
     */
    readonly answers?: string;
    readonly attachments?: Array<ApplicationAttachment>;
    /**
     * Submitted at
     */
    readonly submitted_at?: string;
    /**
     * Created at
     */
    readonly created_at?: string;
    /**
     * Updated at
     */
    readonly updated_at?: string;
    /**
     * Analysis
     */
    readonly analysis?: string;
};

export type UserBasic = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Email
     */
    email: string;
    /**
     * First name
     */
    first_name?: string;
    /**
     * Last name
     */
    last_name?: string;
};

export type OrganizationMembership = {
    /**
     * Id
     */
    readonly id?: string;
    user?: UserBasic;
    /**
     * Role
     */
    role?: 'ORG_ADMIN' | 'MEMBER';
    /**
     * Created at
     */
    readonly created_at?: string;
};

export type PasswordResetRequest = {
    /**
     * Email
     */
    email: string;
};

export type PasswordResetConfirm = {
    /**
     * Token
     */
    token: string;
    /**
     * New password
     */
    new_password: string;
    /**
     * New password confirm
     */
    new_password_confirm: string;
};

export type UserProfile = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Email
     */
    readonly email?: string;
    /**
     * Username
     *
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    /**
     * First name
     */
    first_name?: string;
    /**
     * Last name
     */
    last_name?: string;
    /**
     * Default organization
     *
     * The user's default organization (used for login redirect)
     */
    default_organization?: string | null;
    /**
     * Profile picture url
     */
    readonly profile_picture_url?: string;
    /**
     * Date joined
     */
    readonly date_joined?: string;
};

export type UserUpdate = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Username
     *
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    /**
     * First name
     */
    first_name?: string;
    /**
     * Last name
     */
    last_name?: string;
    /**
     * Default organization
     *
     * The user's default organization (used for login redirect)
     */
    default_organization?: string | null;
};

export type ApplicationAttachmentWritable = {
    /**
     * File name
     *
     * Original filename
     */
    file_name: string;
    /**
     * File type
     */
    file_type?: 'resume' | 'cover_letter' | 'portfolio' | 'certificate' | 'other';
};

export type JobApplicationDetailWritable = {
    /**
     * Job profile
     *
     * Job profile this application is for
     */
    job_profile: string;
    /**
     * First name
     */
    first_name: string;
    /**
     * Last name
     */
    last_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Phone
     */
    phone: string;
    address?: ApplicantAddress;
};

export type QuestionWritable = {
    /**
     * Text
     *
     * Question text
     */
    text: string;
    /**
     * Question type
     */
    question_type?: 'text' | 'mcq' | 'mcq_single';
    /**
     * Order
     *
     * Display order of the question
     */
    order?: number;
    /**
     * Array of choice strings for multiple choice questions
     */
    choices?: Array<string>;
    /**
     * Is required
     *
     * Whether this question must be answered
     */
    is_required?: boolean;
};

export type JobProfileCreateWritable = {
    /**
     * Title
     */
    title: string;
    /**
     * Category
     *
     * Job category
     */
    category: string;
    /**
     * Employment type
     */
    employment_type?: 'full_time' | 'part_time' | 'contract' | 'internship' | 'freelance' | 'not_applicable';
    /**
     * Experience level
     *
     * Required experience level
     */
    experience_level: string;
    /**
     * Description
     *
     * Detailed job description
     */
    description: string;
    qualifications?: Array<QualificationWrite>;
    questions?: Array<QuestionWritable>;
};

export type AddressWritable = {
    /**
     * Line1
     *
     * Street address line 1
     */
    line1: string;
    /**
     * Line2
     *
     * Street address line 2 (optional)
     */
    line2?: string;
    /**
     * City
     */
    city: string;
    /**
     * Province state
     *
     * Province, state, or region
     */
    province_state: string;
    /**
     * Postal code
     */
    postal_code: string;
    /**
     * Country
     *
     * ISO 3166-1 alpha-2 country code
     */
    country: string;
};

export type OrganizationWritable = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     *
     * Description of the organization
     */
    description?: string | null;
    address?: AddressWritable;
};

export type UserWritable = {
    /**
     * Email
     */
    email: string;
    /**
     * Username
     *
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    /**
     * First name
     */
    first_name: string;
    /**
     * Last name
     */
    last_name: string;
    /**
     * Password
     */
    password: string;
    /**
     * Password confirm
     */
    password_confirm: string;
    /**
     * Invitation token
     */
    invitation_token?: string;
};

export type QualificationWritable = {
    /**
     * Category
     */
    category: 'skill' | 'experience' | 'education' | 'certification' | 'tool' | 'language' | 'other';
    /**
     * Name
     */
    name: string;
    /**
     * Requirement level
     */
    requirement_level?: 'required' | 'preferred';
    /**
     * Years required
     */
    years_required?: number | null;
    /**
     * Proficiency level
     */
    proficiency_level?: 'beginner' | 'intermediate' | 'advanced' | 'expert';
    /**
     * Order
     */
    order?: number;
};

export type JobProfileDetailWritable = {
    organization?: OrganizationWritable;
    created_by?: UserWritable;
    /**
     * Title
     */
    title: string;
    /**
     * Employment type
     */
    employment_type?: 'full_time' | 'part_time' | 'contract' | 'internship' | 'freelance' | 'not_applicable';
    /**
     * Description
     *
     * Detailed job description
     */
    description: string;
    /**
     * Is active
     *
     * Whether the job profile is active
     */
    is_active?: boolean;
};

export type OrganizationListWritable = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     *
     * Description of the organization
     */
    description?: string | null;
    address?: AddressWritable;
    /**
     * Status
     */
    status?: 'PENDING' | 'APPROVED' | 'REJECTED' | 'SUSPENDED';
};

export type OrganizationCreateWritable = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     *
     * Description of the organization
     */
    description?: string | null;
    address?: AddressWritable;
};

export type OrganizationInvitationWritable = {
    /**
     * Organization
     */
    organization: string;
    /**
     * Email
     */
    email: string;
    /**
     * Role
     */
    role?: 'ORG_ADMIN' | 'MEMBER';
};

export type JobProfileListWritable = {
    /**
     * Title
     */
    title: string;
    /**
     * Organization
     *
     * Organization that owns this job profile
     */
    organization: string;
    /**
     * Category
     *
     * Job category
     */
    category: string;
    /**
     * Employment type
     */
    employment_type?: 'full_time' | 'part_time' | 'contract' | 'internship' | 'freelance' | 'not_applicable';
    /**
     * Experience level
     *
     * Required experience level
     */
    experience_level: string;
    /**
     * Created by
     *
     * User who created this job profile
     */
    created_by: string;
    /**
     * Is active
     *
     * Whether the job profile is active
     */
    is_active?: boolean;
};

export type JobApplicationDetailWithAnalysisWritable = {
    /**
     * Job profile
     *
     * Job profile this application is for
     */
    job_profile: string;
    /**
     * First name
     */
    first_name: string;
    /**
     * Last name
     */
    last_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Phone
     */
    phone: string;
    address?: ApplicantAddress;
};

export type UserBasicWritable = {
    /**
     * Email
     */
    email: string;
    /**
     * First name
     */
    first_name?: string;
    /**
     * Last name
     */
    last_name?: string;
};

export type OrganizationMembershipWritable = {
    user?: UserBasicWritable;
    /**
     * Role
     */
    role?: 'ORG_ADMIN' | 'MEMBER';
};

export type UserProfileWritable = {
    /**
     * Username
     *
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    /**
     * First name
     */
    first_name?: string;
    /**
     * Last name
     */
    last_name?: string;
    /**
     * Default organization
     *
     * The user's default organization (used for login redirect)
     */
    default_organization?: string | null;
};

export type UserUpdateWritable = {
    /**
     * Username
     *
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    /**
     * First name
     */
    first_name?: string;
    /**
     * Last name
     */
    last_name?: string;
    /**
     * Default organization
     *
     * The user's default organization (used for login redirect)
     */
    default_organization?: string | null;
};

export type ApiApplicationsSubmitCreateData = {
    body: JobApplicationCreate;
    path?: never;
    query?: never;
    url: '/api/applications/submit/';
};

export type ApiApplicationsSubmitCreateErrors = {
    /**
     * Validation error - missing required fields or invalid data
     */
    400: unknown;
};

export type ApiApplicationsSubmitCreateResponses = {
    /**
     * Application submitted successfully
     */
    201: JobApplicationDetail;
};

export type ApiApplicationsSubmitCreateResponse = ApiApplicationsSubmitCreateResponses[keyof ApiApplicationsSubmitCreateResponses];

export type ApiApplicationsSubmitUploadResumeCreateData = {
    body: {
        /**
         * Resume file to upload
         */
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/applications/submit/upload/resume/';
};

export type ApiApplicationsSubmitUploadResumeCreateErrors = {
    /**
     * Validation error - no file provided or file too large
     */
    400: unknown;
};

export type ApiApplicationsSubmitUploadResumeCreateResponses = {
    /**
     * File uploaded successfully
     */
    201: {
        /**
         * Temporary file ID to pass as resume_id on submission
         */
        file_id?: string;
        file_name?: string;
        /**
         * File size in bytes
         */
        file_size?: number;
    };
};

export type ApiApplicationsSubmitUploadResumeCreateResponse = ApiApplicationsSubmitUploadResumeCreateResponses[keyof ApiApplicationsSubmitUploadResumeCreateResponses];

export type ApiApplicationsAnalysisListData = {
    body?: never;
    path: {
        /**
         * Job application UUID
         */
        application_id: string;
    };
    query?: never;
    url: '/api/applications/{application_id}/analysis/';
};

export type ApiApplicationsAnalysisListErrors = {
    /**
     * Application or analysis not found
     */
    404: unknown;
};

export type ApiApplicationsAnalysisListResponses = {
    200: ApplicationAnalysis;
};

export type ApiApplicationsAnalysisListResponse = ApiApplicationsAnalysisListResponses[keyof ApiApplicationsAnalysisListResponses];

export type ApiApplicationsAnalysisRetryCreateData = {
    body?: never;
    path: {
        /**
         * Job application UUID
         */
        application_id: string;
    };
    query?: never;
    url: '/api/applications/{application_id}/analysis/retry/';
};

export type ApiApplicationsAnalysisRetryCreateErrors = {
    /**
     * Analysis is not in FAILED state
     */
    400: unknown;
    /**
     * Application or analysis not found
     */
    404: unknown;
};

export type ApiApplicationsAnalysisRetryCreateResponses = {
    /**
     * Analysis re-triggered
     */
    200: unknown;
};

export type ApiGeoCountriesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/geo/countries/';
};

export type ApiGeoCountriesListResponses = {
    /**
     * List of countries
     */
    200: Array<{
        iso2?: string;
        name?: string;
    }>;
};

export type ApiGeoCountriesListResponse = ApiGeoCountriesListResponses[keyof ApiGeoCountriesListResponses];

export type ApiGeoCountriesStatesListData = {
    body?: never;
    path: {
        /**
         * ISO-2 country code (e.g. US)
         */
        country_code: string;
    };
    query?: never;
    url: '/api/geo/countries/{country_code}/states/';
};

export type ApiGeoCountriesStatesListResponses = {
    /**
     * List of states
     */
    200: Array<{
        iso2?: string;
        name?: string;
    }>;
};

export type ApiGeoCountriesStatesListResponse = ApiGeoCountriesStatesListResponses[keyof ApiGeoCountriesStatesListResponses];

export type ApiGeoCountriesStatesCitiesListData = {
    body?: never;
    path: {
        /**
         * ISO-2 country code (e.g. US)
         */
        country_code: string;
        /**
         * State/province code (e.g. CA)
         */
        state_code: string;
    };
    query?: never;
    url: '/api/geo/countries/{country_code}/states/{state_code}/cities/';
};

export type ApiGeoCountriesStatesCitiesListResponses = {
    /**
     * List of cities
     */
    200: Array<{
        name?: string;
    }>;
};

export type ApiGeoCountriesStatesCitiesListResponse = ApiGeoCountriesStatesCitiesListResponses[keyof ApiGeoCountriesStatesCitiesListResponses];

export type ApiInvitationsAcceptCreateData = {
    body: InvitationAccept;
    path?: never;
    query?: never;
    url: '/api/invitations/accept/';
};

export type ApiInvitationsAcceptCreateErrors = {
    /**
     * Invalid token, email mismatch, or user already in organization
     */
    400: unknown;
    /**
     * Authentication required
     */
    401: unknown;
};

export type ApiInvitationsAcceptCreateResponses = {
    /**
     * Invitation accepted successfully
     */
    200: {
        message?: string;
        /**
         * Organization details
         */
        organization?: {
            [key: string]: unknown;
        };
        /**
         * Membership details
         */
        membership?: {
            [key: string]: unknown;
        };
    };
};

export type ApiInvitationsAcceptCreateResponse = ApiInvitationsAcceptCreateResponses[keyof ApiInvitationsAcceptCreateResponses];

export type ApiInvitationsValidateCreateData = {
    body: InvitationValidate;
    path?: never;
    query?: never;
    url: '/api/invitations/validate/';
};

export type ApiInvitationsValidateCreateErrors = {
    /**
     * Invalid, expired, or already accepted token
     */
    400: unknown;
};

export type ApiInvitationsValidateCreateResponses = {
    /**
     * Invitation is valid
     */
    200: {
        valid?: boolean;
        organization_name?: string;
        role?: string;
        email?: string;
        invited_by?: string;
        expires_at?: string;
    };
};

export type ApiInvitationsValidateCreateResponse = ApiInvitationsValidateCreateResponses[keyof ApiInvitationsValidateCreateResponses];

export type ApiJobProfilesCreateCreateData = {
    body: JobProfileCreateWritable;
    path?: never;
    query?: never;
    url: '/api/job-profiles/create/';
};

export type ApiJobProfilesCreateCreateErrors = {
    /**
     * Validation error
     */
    400: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ApiJobProfilesCreateCreateResponses = {
    201: JobProfileDetail;
};

export type ApiJobProfilesCreateCreateResponse = ApiJobProfilesCreateCreateResponses[keyof ApiJobProfilesCreateCreateResponses];

export type ApiJobProfilesExperienceLevelsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/job-profiles/experience-levels/';
};

export type ApiJobProfilesExperienceLevelsListResponses = {
    200: Array<ExperienceLevel>;
};

export type ApiJobProfilesExperienceLevelsListResponse = ApiJobProfilesExperienceLevelsListResponses[keyof ApiJobProfilesExperienceLevelsListResponses];

export type ApiJobProfilesJobCategoriesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/job-profiles/job-categories/';
};

export type ApiJobProfilesJobCategoriesListResponses = {
    200: Array<JobCategory>;
};

export type ApiJobProfilesJobCategoriesListResponse = ApiJobProfilesJobCategoriesListResponses[keyof ApiJobProfilesJobCategoriesListResponses];

export type ApiJobProfilesReadData = {
    body?: never;
    path: {
        /**
         * Job Profile UUID
         */
        job_id: string;
    };
    query?: never;
    url: '/api/job-profiles/{job_id}/';
};

export type ApiJobProfilesReadResponses = {
    200: JobProfileDetail;
};

export type ApiJobProfilesReadResponse = ApiJobProfilesReadResponses[keyof ApiJobProfilesReadResponses];

export type ApiJobProfilesUpdatePartialUpdateData = {
    body: JobProfileCreateWritable;
    path: {
        /**
         * Job Profile UUID
         */
        job_id: string;
    };
    query?: never;
    url: '/api/job-profiles/{job_id}/update/';
};

export type ApiJobProfilesUpdatePartialUpdateErrors = {
    /**
     * Validation error
     */
    400: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ApiJobProfilesUpdatePartialUpdateResponses = {
    200: JobProfileDetail;
};

export type ApiJobProfilesUpdatePartialUpdateResponse = ApiJobProfilesUpdatePartialUpdateResponses[keyof ApiJobProfilesUpdatePartialUpdateResponses];

export type ApiOrganizationsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/organizations/';
};

export type ApiOrganizationsListErrors = {
    /**
     * User does not belong to any organization
     */
    404: unknown;
};

export type ApiOrganizationsListResponses = {
    200: Array<OrganizationList>;
};

export type ApiOrganizationsListResponse = ApiOrganizationsListResponses[keyof ApiOrganizationsListResponses];

export type ApiOrganizationsCreateCreateData = {
    body: OrganizationCreateWritable;
    path?: never;
    query?: never;
    url: '/api/organizations/create/';
};

export type ApiOrganizationsCreateCreateErrors = {
    /**
     * Validation error
     */
    400: unknown;
};

export type ApiOrganizationsCreateCreateResponses = {
    /**
     * Organization created successfully
     */
    201: Organization;
};

export type ApiOrganizationsCreateCreateResponse = ApiOrganizationsCreateCreateResponses[keyof ApiOrganizationsCreateCreateResponses];

export type ApiOrganizationsReadData = {
    body?: never;
    path: {
        org_id: string;
    };
    query?: never;
    url: '/api/organizations/{org_id}/';
};

export type ApiOrganizationsReadErrors = {
    /**
     * User is not a member of this organization
     */
    403: unknown;
    /**
     * Organization not found
     */
    404: unknown;
};

export type ApiOrganizationsReadResponses = {
    200: Organization;
};

export type ApiOrganizationsReadResponse = ApiOrganizationsReadResponses[keyof ApiOrganizationsReadResponses];

export type ApiOrganizationsAnalyticsListData = {
    body?: never;
    path: {
        /**
         * Organization UUID
         */
        org_id: string;
    };
    query?: never;
    url: '/api/organizations/{org_id}/analytics/';
};

export type ApiOrganizationsAnalyticsListResponses = {
    /**
     * Org analytics object
     */
    200: unknown;
};

export type ApiOrganizationsInvitationsCreateData = {
    body: InvitationCreate;
    path: {
        /**
         * UUID of the organization
         */
        org_id: string;
    };
    query?: never;
    url: '/api/organizations/{org_id}/invitations/';
};

export type ApiOrganizationsInvitationsCreateErrors = {
    /**
     * Validation error or organization not approved
     */
    400: unknown;
    /**
     * Only organization admins can send invitations
     */
    403: unknown;
    /**
     * Organization not found
     */
    404: unknown;
};

export type ApiOrganizationsInvitationsCreateResponses = {
    /**
     * Invitation created and email sent
     */
    201: OrganizationInvitation;
};

export type ApiOrganizationsInvitationsCreateResponse = ApiOrganizationsInvitationsCreateResponses[keyof ApiOrganizationsInvitationsCreateResponses];

export type ApiOrganizationsInvitationsListListData = {
    body?: never;
    path: {
        /**
         * UUID of the organization
         */
        org_id: string;
    };
    query?: never;
    url: '/api/organizations/{org_id}/invitations/list/';
};

export type ApiOrganizationsInvitationsListListErrors = {
    /**
     * Only organization members can view invitations
     */
    403: unknown;
    /**
     * Organization not found
     */
    404: unknown;
};

export type ApiOrganizationsInvitationsListListResponses = {
    /**
     * List of invitations
     */
    200: Array<OrganizationInvitation>;
};

export type ApiOrganizationsInvitationsListListResponse = ApiOrganizationsInvitationsListListResponses[keyof ApiOrganizationsInvitationsListListResponses];

export type ApiOrganizationsJobProfilesListData = {
    body?: never;
    path: {
        /**
         * Organization UUID
         */
        org_id: string;
    };
    query?: never;
    url: '/api/organizations/{org_id}/job-profiles/';
};

export type ApiOrganizationsJobProfilesListResponses = {
    200: Array<JobProfileList>;
};

export type ApiOrganizationsJobProfilesListResponse = ApiOrganizationsJobProfilesListResponses[keyof ApiOrganizationsJobProfilesListResponses];

export type ApiOrganizationsJobProfilesAnalysesListData = {
    body?: never;
    path: {
        /**
         * Organization UUID
         */
        org_id: string;
        /**
         * Job profile UUID
         */
        job_profile_id: string;
    };
    query?: {
        /**
         * Filter by pipeline status
         */
        status?: 'uploaded' | 'ocr_pending' | 'ocr_done' | 'ai_pending' | 'done' | 'failed';
        /**
         * Minimum AI score (0-100, inclusive)
         */
        min_score?: number;
        /**
         * Maximum AI score (0-100, inclusive)
         */
        max_score?: number;
        /**
         * Field to sort by
         */
        sort_by?: 'score' | 'created_at' | 'updated_at';
        /**
         * Sort direction
         */
        order?: 'asc' | 'desc';
        /**
         * Page number (default: 1)
         */
        page?: number;
        /**
         * Results per page, max 100 (default: 20)
         */
        page_size?: number;
    };
    url: '/api/organizations/{org_id}/job-profiles/{job_profile_id}/analyses/';
};

export type ApiOrganizationsJobProfilesAnalysesListErrors = {
    /**
     * Invalid query parameter
     */
    400: unknown;
    /**
     * Not a member of the organization
     */
    403: unknown;
    /**
     * Organization or job profile not found
     */
    404: unknown;
};

export type ApiOrganizationsJobProfilesAnalysesListResponses = {
    /**
     * Paginated list of analyses
     */
    200: {
        /**
         * Total number of results
         */
        count?: number;
        total_pages?: number;
        /**
         * Current page
         */
        page?: number;
        page_size?: number;
        results?: Array<{
            [key: string]: unknown;
        }>;
    };
};

export type ApiOrganizationsJobProfilesAnalysesListResponse = ApiOrganizationsJobProfilesAnalysesListResponses[keyof ApiOrganizationsJobProfilesAnalysesListResponses];

export type ApiOrganizationsJobProfilesAnalyticsListData = {
    body?: never;
    path: {
        /**
         * Organization UUID
         */
        org_id: string;
        /**
         * Job profile UUID
         */
        job_profile_id: string;
    };
    query?: never;
    url: '/api/organizations/{org_id}/job-profiles/{job_profile_id}/analytics/';
};

export type ApiOrganizationsJobProfilesAnalyticsListResponses = {
    /**
     * Analytics object
     */
    200: unknown;
};

export type ApiOrganizationsJobProfilesApplicationsListData = {
    body?: never;
    path: {
        /**
         * Organization UUID
         */
        org_id: string;
        job_profile_id: string;
    };
    query?: {
        /**
         * Page number (1-based, default 1)
         */
        page?: number;
        /**
         * Results per page (default 10, max 100)
         */
        page_size?: number;
        /**
         * Search by first name, last name, or email
         */
        search?: string;
        /**
         * Filter by application status (to_be_reviewed, reviewed, shortlisted, rejected)
         */
        status?: string;
        /**
         * Sort field. Prefix with '-' for descending. Options: submitted_at, first_name, last_name, status, score
         */
        ordering?: string;
    };
    url: '/api/organizations/{org_id}/job-profiles/{job_profile_id}/applications/';
};

export type ApiOrganizationsJobProfilesApplicationsListErrors = {
    /**
     * Forbidden - user is not a member of the organization
     */
    403: unknown;
    /**
     * Organization or job profile not found
     */
    404: unknown;
};

export type ApiOrganizationsJobProfilesApplicationsListResponses = {
    /**
     * Paginated list of job applications
     */
    200: {
        count?: number;
        page?: number;
        page_size?: number;
        num_pages?: number;
        results?: Array<{
            [key: string]: unknown;
        }>;
    };
};

export type ApiOrganizationsJobProfilesApplicationsListResponse = ApiOrganizationsJobProfilesApplicationsListResponses[keyof ApiOrganizationsJobProfilesApplicationsListResponses];

export type ApiOrganizationsJobProfilesApplicationsReadData = {
    body?: never;
    path: {
        /**
         * Organization UUID
         */
        org_id: string;
        /**
         * Job profile UUID (must belong to the organization)
         */
        job_profile_id: string;
        /**
         * Job application UUID
         */
        job_application_id: string;
    };
    query?: never;
    url: '/api/organizations/{org_id}/job-profiles/{job_profile_id}/applications/{job_application_id}/';
};

export type ApiOrganizationsJobProfilesApplicationsReadErrors = {
    /**
     * Forbidden - user is not a member of the organization
     */
    403: unknown;
    /**
     * Organization, job profile, or job application not found
     */
    404: unknown;
};

export type ApiOrganizationsJobProfilesApplicationsReadResponses = {
    200: JobApplicationDetailWithAnalysis;
};

export type ApiOrganizationsJobProfilesApplicationsReadResponse = ApiOrganizationsJobProfilesApplicationsReadResponses[keyof ApiOrganizationsJobProfilesApplicationsReadResponses];

export type ApiOrganizationsJobProfilesApplicationsDownloadListData = {
    body?: never;
    path: {
        /**
         * Organization UUID
         */
        org_id: string;
        /**
         * Job profile UUID (must belong to the organization)
         */
        job_profile_id: string;
        /**
         * Job application UUID
         */
        job_application_id: string;
    };
    query?: never;
    url: '/api/organizations/{org_id}/job-profiles/{job_profile_id}/applications/{job_application_id}/download/';
};

export type ApiOrganizationsJobProfilesApplicationsDownloadListErrors = {
    /**
     * Resume not found
     */
    404: unknown;
};

export type ApiOrganizationsJobProfilesApplicationsDownloadListResponses = {
    /**
     * File download
     */
    200: unknown;
};

export type ApiOrganizationsJobProfilesApplicationsStatusPartialUpdateData = {
    body: {
        status: 'to_be_reviewed' | 'reviewed' | 'shortlisted' | 'rejected';
    };
    path: {
        /**
         * Organization UUID
         */
        org_id: string;
        /**
         * Job profile UUID
         */
        job_profile_id: string;
        /**
         * Job application UUID
         */
        job_application_id: string;
    };
    query?: never;
    url: '/api/organizations/{org_id}/job-profiles/{job_profile_id}/applications/{job_application_id}/status/';
};

export type ApiOrganizationsJobProfilesApplicationsStatusPartialUpdateErrors = {
    /**
     * Invalid status transition
     */
    400: unknown;
    /**
     * Not found
     */
    404: unknown;
};

export type ApiOrganizationsJobProfilesApplicationsStatusPartialUpdateResponses = {
    200: JobApplicationDetail;
};

export type ApiOrganizationsJobProfilesApplicationsStatusPartialUpdateResponse = ApiOrganizationsJobProfilesApplicationsStatusPartialUpdateResponses[keyof ApiOrganizationsJobProfilesApplicationsStatusPartialUpdateResponses];

export type ApiOrganizationsLeaveDeleteData = {
    body?: never;
    path: {
        /**
         * UUID of the organization
         */
        org_id: string;
    };
    query?: never;
    url: '/api/organizations/{org_id}/leave/';
};

export type ApiOrganizationsLeaveDeleteErrors = {
    /**
     * Cannot leave - you are the last admin
     */
    400: unknown;
    /**
     * You are not a member of this organization
     */
    403: unknown;
    /**
     * Organization not found
     */
    404: unknown;
};

export type ApiOrganizationsLeaveDeleteResponses = {
    /**
     * Successfully left the organization
     */
    204: unknown;
};

export type ApiOrganizationsMembersListData = {
    body?: never;
    path: {
        org_id: string;
    };
    query?: never;
    url: '/api/organizations/{org_id}/members/';
};

export type ApiOrganizationsMembersListErrors = {
    /**
     * User is not a member of this organization
     */
    403: unknown;
    /**
     * Organization not found
     */
    404: unknown;
};

export type ApiOrganizationsMembersListResponses = {
    /**
     * List of organization members
     */
    200: Array<OrganizationMembership>;
};

export type ApiOrganizationsMembersListResponse = ApiOrganizationsMembersListResponses[keyof ApiOrganizationsMembersListResponses];

export type ApiOrganizationsMembersDeleteData = {
    body?: never;
    path: {
        /**
         * UUID of the organization
         */
        org_id: string;
        /**
         * UUID of the membership to remove
         */
        membership_id: string;
    };
    query?: never;
    url: '/api/organizations/{org_id}/members/{membership_id}/';
};

export type ApiOrganizationsMembersDeleteErrors = {
    /**
     * Cannot remove the last admin
     */
    400: unknown;
    /**
     * Only organization admins can remove members
     */
    403: unknown;
    /**
     * Organization or membership not found
     */
    404: unknown;
};

export type ApiOrganizationsMembersDeleteResponses = {
    /**
     * Member removed successfully
     */
    204: unknown;
};

export type ApiOrganizationsProfilePictureCreateData = {
    body: {
        /**
         * Profile picture file (JPEG, PNG, or WebP)
         */
        file: Blob | File;
    };
    path: {
        /**
         * Organization UUID
         */
        org_id: string;
    };
    query?: never;
    url: '/api/organizations/{org_id}/profile-picture/';
};

export type ApiOrganizationsProfilePictureCreateErrors = {
    /**
     * Invalid file
     */
    400: unknown;
    /**
     * Not an admin
     */
    403: unknown;
    /**
     * Organization not found
     */
    404: unknown;
};

export type ApiOrganizationsProfilePictureCreateResponses = {
    /**
     * Organization with updated picture
     */
    200: Organization;
};

export type ApiOrganizationsProfilePictureCreateResponse = ApiOrganizationsProfilePictureCreateResponses[keyof ApiOrganizationsProfilePictureCreateResponses];

export type ApiOrganizationsProfilePictureDeleteDeleteData = {
    body?: never;
    path: {
        /**
         * Organization UUID
         */
        org_id: string;
    };
    query?: never;
    url: '/api/organizations/{org_id}/profile-picture/delete/';
};

export type ApiOrganizationsProfilePictureDeleteDeleteErrors = {
    /**
     * Not an admin
     */
    403: unknown;
    /**
     * Organization not found
     */
    404: unknown;
};

export type ApiOrganizationsProfilePictureDeleteDeleteResponses = {
    /**
     * Organization with picture removed
     */
    200: Organization;
};

export type ApiOrganizationsProfilePictureDeleteDeleteResponse = ApiOrganizationsProfilePictureDeleteDeleteResponses[keyof ApiOrganizationsProfilePictureDeleteDeleteResponses];

export type ApiOrganizationsUpdatePartialUpdateData = {
    body: OrganizationCreateWritable;
    path: {
        org_id: string;
    };
    query?: never;
    url: '/api/organizations/{org_id}/update/';
};

export type ApiOrganizationsUpdatePartialUpdateErrors = {
    /**
     * User is not an admin of this organization
     */
    403: unknown;
    /**
     * Organization not found
     */
    404: unknown;
};

export type ApiOrganizationsUpdatePartialUpdateResponses = {
    200: Organization;
};

export type ApiOrganizationsUpdatePartialUpdateResponse = ApiOrganizationsUpdatePartialUpdateResponses[keyof ApiOrganizationsUpdatePartialUpdateResponses];

export type ApiTestResumeExtractionCreateData = {
    body: {
        /**
         * PDF file to extract text from
         */
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/test-resume-extraction/';
};

export type ApiTestResumeExtractionCreateErrors = {
    /**
     * No file provided
     */
    400: unknown;
};

export type ApiTestResumeExtractionCreateResponses = {
    /**
     * Extracted text
     */
    200: {
        text?: string;
        pages?: number;
    };
};

export type ApiTestResumeExtractionCreateResponse = ApiTestResumeExtractionCreateResponses[keyof ApiTestResumeExtractionCreateResponses];

export type ApiUsersAuthLoginCreateData = {
    body: {
        /**
         * User's email address
         */
        email: string;
        /**
         * User's password
         */
        password: string;
    };
    path?: never;
    query?: never;
    url: '/api/users/auth/login/';
};

export type ApiUsersAuthLoginCreateErrors = {
    /**
     * Invalid credentials
     */
    401: unknown;
};

export type ApiUsersAuthLoginCreateResponses = {
    /**
     * Login successful
     */
    200: {
        /**
         * Access token
         */
        access?: string;
        /**
         * Refresh token
         */
        refresh?: string;
    };
};

export type ApiUsersAuthLoginCreateResponse = ApiUsersAuthLoginCreateResponses[keyof ApiUsersAuthLoginCreateResponses];

export type ApiUsersAuthRegisterCreateData = {
    body: UserWritable;
    path?: never;
    query?: never;
    url: '/api/users/auth/register/';
};

export type ApiUsersAuthRegisterCreateErrors = {
    /**
     * Validation error or invalid invitation token
     */
    400: unknown;
};

export type ApiUsersAuthRegisterCreateResponses = {
    /**
     * User created successfully
     */
    201: User;
};

export type ApiUsersAuthRegisterCreateResponse = ApiUsersAuthRegisterCreateResponses[keyof ApiUsersAuthRegisterCreateResponses];

export type ApiUsersAuthTokenRefreshCreateData = {
    body: {
        /**
         * The refresh token obtained from login
         */
        refresh: string;
    };
    path?: never;
    query?: never;
    url: '/api/users/auth/token/refresh/';
};

export type ApiUsersAuthTokenRefreshCreateErrors = {
    /**
     * Invalid or expired refresh token
     */
    401: unknown;
};

export type ApiUsersAuthTokenRefreshCreateResponses = {
    /**
     * Token refresh successful
     */
    200: {
        /**
         * New JWT access token (expires in 1 hour)
         */
        access?: string;
        /**
         * New JWT refresh token (expires in 7 days, rotation enabled)
         */
        refresh?: string;
    };
};

export type ApiUsersAuthTokenRefreshCreateResponse = ApiUsersAuthTokenRefreshCreateResponses[keyof ApiUsersAuthTokenRefreshCreateResponses];

export type ApiUsersPasswordResetCreateData = {
    body: PasswordResetRequest;
    path?: never;
    query?: never;
    url: '/api/users/password-reset/';
};

export type ApiUsersPasswordResetCreateErrors = {
    /**
     * Invalid data
     */
    400: unknown;
};

export type ApiUsersPasswordResetCreateResponses = {
    /**
     * Password reset email sent (if email exists)
     */
    200: {
        /**
         * Success message
         */
        message?: string;
    };
};

export type ApiUsersPasswordResetCreateResponse = ApiUsersPasswordResetCreateResponses[keyof ApiUsersPasswordResetCreateResponses];

export type ApiUsersPasswordResetConfirmCreateData = {
    body: PasswordResetConfirm;
    path?: never;
    query?: never;
    url: '/api/users/password-reset/confirm/';
};

export type ApiUsersPasswordResetConfirmCreateErrors = {
    /**
     * Validation error or invalid token
     */
    400: unknown;
};

export type ApiUsersPasswordResetConfirmCreateResponses = {
    /**
     * Password reset successful
     */
    200: {
        /**
         * Success message
         */
        message?: string;
    };
};

export type ApiUsersPasswordResetConfirmCreateResponse = ApiUsersPasswordResetConfirmCreateResponses[keyof ApiUsersPasswordResetConfirmCreateResponses];

export type ApiUsersProfileListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/profile/';
};

export type ApiUsersProfileListErrors = {
    /**
     * Not authenticated
     */
    401: unknown;
};

export type ApiUsersProfileListResponses = {
    /**
     * User profile
     */
    200: UserProfile;
};

export type ApiUsersProfileListResponse = ApiUsersProfileListResponses[keyof ApiUsersProfileListResponses];

export type ApiUsersProfileDefaultOrganizationPartialUpdateData = {
    body: {
        /**
         * Organization UUID to set as default, or null to clear
         */
        default_organization: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/users/profile/default-organization/';
};

export type ApiUsersProfileDefaultOrganizationPartialUpdateErrors = {
    /**
     * Validation error (e.g., not a member of the organization)
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
};

export type ApiUsersProfileDefaultOrganizationPartialUpdateResponses = {
    /**
     * Default organization updated
     */
    200: UserProfile;
};

export type ApiUsersProfileDefaultOrganizationPartialUpdateResponse = ApiUsersProfileDefaultOrganizationPartialUpdateResponses[keyof ApiUsersProfileDefaultOrganizationPartialUpdateResponses];

export type ApiUsersProfilePictureCreateData = {
    body: {
        /**
         * Profile picture file (JPEG, PNG, or WebP)
         */
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/users/profile/picture/';
};

export type ApiUsersProfilePictureCreateErrors = {
    /**
     * Invalid file
     */
    400: unknown;
};

export type ApiUsersProfilePictureCreateResponses = {
    /**
     * Profile with updated picture URL
     */
    200: UserProfile;
};

export type ApiUsersProfilePictureCreateResponse = ApiUsersProfilePictureCreateResponses[keyof ApiUsersProfilePictureCreateResponses];

export type ApiUsersProfilePictureDeleteDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/profile/picture/delete/';
};

export type ApiUsersProfilePictureDeleteDeleteResponses = {
    /**
     * Profile with picture removed
     */
    200: UserProfile;
};

export type ApiUsersProfilePictureDeleteDeleteResponse = ApiUsersProfilePictureDeleteDeleteResponses[keyof ApiUsersProfilePictureDeleteDeleteResponses];

export type ApiUsersProfileUpdatePartialUpdateData = {
    body: UserUpdateWritable;
    path?: never;
    query?: never;
    url: '/api/users/profile/update/';
};

export type ApiUsersProfileUpdatePartialUpdateErrors = {
    /**
     * Validation error
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
};

export type ApiUsersProfileUpdatePartialUpdateResponses = {
    /**
     * Profile updated successfully
     */
    200: UserProfile;
};

export type ApiUsersProfileUpdatePartialUpdateResponse = ApiUsersProfileUpdatePartialUpdateResponses[keyof ApiUsersProfileUpdatePartialUpdateResponses];

export type HealthListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/';
};

export type HealthListResponses = {
    /**
     * OK
     */
    200: {
        /**
         * Status of the application
         */
        status?: string;
    };
};

export type HealthListResponse = HealthListResponses[keyof HealthListResponses];
