# Generated by Django 6.0.1 on 2026-02-08 05:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_profile', '0004_jobprofile_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_profile', models.ForeignKey(help_text='Job profile this application is for', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job_profile.jobprofile')),
            ],
            options={
                'db_table': 'job_applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Uploaded file', upload_to='job_applications/%Y/%m/%d/')),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_type', models.CharField(choices=[('resume', 'Resume'), ('cover_letter', 'Cover Letter'), ('portfolio', 'Portfolio'), ('certificate', 'Certificate'), ('other', 'Other')], default='other', max_length=20)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.ForeignKey(help_text='Job application this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='job_applications.jobapplication')),
            ],
            options={
                'db_table': 'application_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('province_state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=2)),
                ('job_application', models.OneToOneField(help_text='Job application this address belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='address', to='job_applications.jobapplication')),
            ],
            options={
                'db_table': 'applicant_addresses',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, help_text='Answer text for text-type questions', null=True)),
                ('selected_choices', models.JSONField(blank=True, default=list, help_text='Selected choices for MCQ questions (array of strings)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.ForeignKey(help_text='Job application this answer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='job_applications.jobapplication')),
                ('question', models.ForeignKey(help_text='Question being answered', on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='job_profile.question')),
            ],
            options={
                'db_table': 'question_answers',
            },
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job_profile', 'status'], name='job_applica_job_pro_aaaed1_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['email'], name='job_applica_email_ac334c_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationattachment',
            index=models.Index(fields=['job_application', 'file_type'], name='application_job_app_9e89bf_idx'),
        ),
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['job_application'], name='question_an_job_app_14b672_idx'),
        ),
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['question'], name='question_an_questio_00b031_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionanswer',
            unique_together={('job_application', 'question')},
        ),
    ]
