# Generated by Django 6.0.1 on 2026-02-22 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_applications', '0001_initial'),
        ('job_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_profile',
            field=models.ForeignKey(help_text='Job profile this application is for', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job_profile.jobprofile'),
        ),
        migrations.AddField(
            model_name='applicationattachment',
            name='job_application',
            field=models.ForeignKey(help_text='Job application this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='job_applications.jobapplication'),
        ),
        migrations.AddField(
            model_name='applicantaddress',
            name='job_application',
            field=models.OneToOneField(help_text='Job application this address belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='address', to='job_applications.jobapplication'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='job_application',
            field=models.ForeignKey(help_text='Job application this answer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='job_applications.jobapplication'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(help_text='Question being answered', on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='job_profile.question'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job_profile', 'status'], name='job_applica_job_pro_aaaed1_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['email'], name='job_applica_email_ac334c_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationattachment',
            index=models.Index(fields=['job_application', 'file_type'], name='application_job_app_9e89bf_idx'),
        ),
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['job_application'], name='question_an_job_app_14b672_idx'),
        ),
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['question'], name='question_an_questio_00b031_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionanswer',
            unique_together={('job_application', 'question')},
        ),
    ]
