# Generated by Django 6.0.1 on 2026-02-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0003_temporaryfileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationattachment',
            name='file',
            field=models.CharField(help_text='Storage path / S3 key of the uploaded file', max_length=500),
        ),
    ]
