# Generated by Django 6.0.1 on 2026-02-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0004_alter_applicationattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationattachment',
            name='sha256_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hex digest of the file contents for deduplication', max_length=64),
        ),
        migrations.AddField(
            model_name='temporaryfileupload',
            name='sha256_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hex digest computed at upload time', max_length=64),
        ),
    ]
