# Generated by Django 6.0.1 on 2026-03-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0005_applicationattachment_sha256_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('to_be_reviewed', 'To Be Reviewed'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='to_be_reviewed', max_length=20),
        ),
    ]
