# Generated by Django 6.0.1 on 2026-03-04 10:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0007_migrate_status_to_to_be_reviewed'),
        ('job_profile', '0006_alter_qualification_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_status', models.CharField(blank=True, choices=[('to_be_reviewed', 'To Be Reviewed'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], help_text='Filter applications to this status. Blank = all statuses.', max_length=20)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX')], default='xlsx', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, help_text='Storage path of the generated file', max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_profile', models.ForeignKey(help_text='Job profile whose applications are being exported', on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='job_profile.jobprofile')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application_export_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
