# Generated by Django 6.0.1 on 2026-02-07 13:49

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIScreeningConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_screening_configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'experience_levels',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Job Categories',
                'db_table': 'job_categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('not_applicable', 'Not Applicable')], default='full_time', max_length=20)),
                ('description', models.TextField(help_text='Detailed job description')),
                ('requirements', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, help_text='List of job requirements')),
                ('skills', models.JSONField(blank=True, default=list, help_text="Array of skill objects with 'skill' and 'is_required' fields")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_screening_configuration', models.ForeignKey(blank=True, help_text='AI screening configuration for this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_profiles', to='job_profile.aiscreeningconfiguration')),
                ('category', models.ForeignKey(help_text='Job category', on_delete=django.db.models.deletion.PROTECT, related_name='job_profiles', to='job_profile.jobcategory')),
                ('experience_level', models.ForeignKey(help_text='Required experience level', on_delete=django.db.models.deletion.PROTECT, related_name='job_profiles', to='job_profile.experiencelevel')),
            ],
            options={
                'db_table': 'job_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
