# Generated by Django 6.0.1 on 2026-02-07 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profile', '0001_initial'),
        ('organizations', '0007_organization_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='User who created this job profile', on_delete=django.db.models.deletion.CASCADE, related_name='created_job_profiles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='organization',
            field=models.ForeignKey(default=1, help_text='Organization that owns this job profile', on_delete=django.db.models.deletion.CASCADE, related_name='job_profiles', to='organizations.organization'),
            preserve_default=False,
        ),
    ]
