# Generated by Django 6.0.1 on 2026-02-22 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_profile', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this job profile', on_delete=django.db.models.deletion.CASCADE, related_name='created_job_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='experience_level',
            field=models.ForeignKey(help_text='Required experience level', on_delete=django.db.models.deletion.PROTECT, related_name='job_profiles', to='job_profile.experiencelevel'),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this job profile', on_delete=django.db.models.deletion.CASCADE, related_name='job_profiles', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='question',
            name='job_profile',
            field=models.ForeignKey(help_text='Job profile this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='job_profile.jobprofile'),
        ),
    ]
