# Generated by Django 6.0.1 on 2026-02-22 13:08
# Manually amended: jsonb cannot be cast directly to text[]; use RunSQL with
# an explicit USING expression to unpack the JSON array into a native text[].

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_profile", "0002_initial"),
    ]

    operations = [
        # Step 1: convert the column data at the DB level using a safe USING clause.
        # jsonb cannot be cast directly to text[]; go via text representation:
        #   ["a","b"] → {"a","b"}  (replace brackets with braces, then cast)
        migrations.RunSQL(
            sql="""
                ALTER TABLE "questions"
                    ALTER COLUMN "choices"
                    TYPE text[]
                    USING translate("choices"::text, '[]', '{}')::text[];
            """,
            reverse_sql="""
                ALTER TABLE "questions"
                    ALTER COLUMN "choices"
                    TYPE jsonb
                    USING to_jsonb("choices");
            """,
        ),
        # Step 2: update Django's migration state so it knows the field type changed.
        migrations.AlterField(
            model_name="question",
            name="choices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                default=list,
                help_text="Array of choice strings for multiple choice questions",
            ),
        ),
    ]
