# Generated by Django 6.0.1 on 2026-02-07 17:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profile', '0002_jobprofile_created_by_jobprofile_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Question text')),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('mcq', 'Multiple Choice')], default='text', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of the question')),
                ('choices', models.JSONField(blank=True, default=list, help_text='Array of choice strings for multiple choice questions')),
                ('is_required', models.BooleanField(default=True, help_text='Whether this question must be answered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_profile', models.ForeignKey(help_text='Job profile this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='job_profile.jobprofile')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['job_profile', 'order'],
            },
        ),
    ]
