# Generated by Django 6.0.1 on 2026-02-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profile', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the job profile is active'),
        ),
    ]
