# Generated by Django 6.0.1 on 2026-02-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profile', '0003_alter_question_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('mcq', 'Multiple Choice (Multi-Select)'), ('mcq_single', 'Multiple Choice (Single Select)')], default='text', max_length=10),
        ),
    ]
