# Generated by Django 6.0.1 on 2026-03-04 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profile', '0004_alter_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobprofile',
            name='ai_screening_configuration',
        ),
        migrations.RemoveField(
            model_name='jobprofile',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='jobprofile',
            name='skills',
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('skill', 'Skill'), ('experience', 'Experience'), ('education', 'Education'), ('certification', 'Certification'), ('tool', 'Tool'), ('language', 'Language')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('requirement_level', models.CharField(choices=[('required', 'Required'), ('preferred', 'Preferred')], default='required', max_length=10)),
                ('years_required', models.PositiveIntegerField(blank=True, null=True)),
                ('proficiency_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=15, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='job_profile.jobprofile')),
            ],
            options={
                'db_table': 'qualifications',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='AIScreeningConfiguration',
        ),
    ]
