# Generated by Django 6.0.1 on 2026-03-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profile', '0005_remove_jobprofile_ai_screening_configuration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='category',
            field=models.CharField(choices=[('skill', 'Skill'), ('experience', 'Experience'), ('education', 'Education'), ('certification', 'Certification'), ('tool', 'Tool'), ('language', 'Language'), ('other', 'Other')], max_length=20),
        ),
    ]
