# Generated by Django 6.0.1 on 2026-03-26 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profile', '0006_alter_qualification_category'),
        ('organizations', '0003_organization_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencelevel',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_experience_levels', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_job_categories', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='experiencelevel',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='experiencelevel',
            constraint=models.UniqueConstraint(condition=models.Q(('organization', None)), fields=('title',), name='unique_global_experience_level_title'),
        ),
        migrations.AddConstraint(
            model_name='experiencelevel',
            constraint=models.UniqueConstraint(fields=('organization', 'title'), name='unique_org_experience_level_title'),
        ),
        migrations.AddConstraint(
            model_name='jobcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('organization', None)), fields=('title',), name='unique_global_job_category_title'),
        ),
        migrations.AddConstraint(
            model_name='jobcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'title'), name='unique_org_job_category_title'),
        ),
    ]
