# Generated by Django 6.0.1 on 2026-04-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profile', '0007_experiencelevel_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft-delete timestamp; non-null means the job profile has been deleted', null=True),
        ),
    ]
