# Generated by Django 6.0.1 on 2026-02-23 05:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_applications', '0005_applicationattachment_sha256_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('ocr_pending', 'OCR Pending'), ('ocr_done', 'OCR Done'), ('ai_pending', 'AI Pending'), ('done', 'Done'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details when status is FAILED')),
                ('extracted_resume_text', models.TextField(blank=True, help_text='Full text extracted from the resume PDF via doctr')),
                ('ai_analysis_summary', models.TextField(blank=True, help_text='High-level summary from AI')),
                ('notable_traits', models.JSONField(blank=True, default=list, help_text='Array of notable trait strings')),
                ('key_skills', models.JSONField(blank=True, default=list, help_text='Array of key skill strings')),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='AI-assigned score 0-100', null=True)),
                ('detailed_analysis', models.JSONField(blank=True, help_text='Structured object: strengths, areas_for_development, experience[], education[], certifications[]', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_application', models.OneToOneField(help_text='The job application being analysed', on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='job_applications.jobapplication')),
            ],
            options={
                'db_table': 'application_analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
