# Generated by Django 6.0.1 on 2026-04-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application_analysis', '0005_remove_score_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationanalysis',
            name='extracted_resume_text',
            field=models.TextField(blank=True, help_text='Full text extracted from the resume PDF via Tesseract OCR'),
        ),
    ]
