# Generated by Django 6.0.1 on 2026-02-05 08:16
# Custom migration to move User model from organizations to users app

from django.db import migrations


def move_user_model(apps, schema_editor):
    """
    Update Django's content type to reflect the User model moving to users app.
    The database table stays the same ('users'), we're just updating Django's metadata.
    """
    ContentType = apps.get_model("contenttypes", "ContentType")

    # Update the content type from organizations.user to users.user
    try:
        user_content_type = ContentType.objects.get(
            app_label="organizations", model="user"
        )
        user_content_type.app_label = "users"
        user_content_type.save()
    except ContentType.DoesNotExist:
        # If it doesn't exist under organizations, it might already be under users
        pass


def reverse_move_user_model(apps, schema_editor):
    """
    Reverse the content type change
    """
    ContentType = apps.get_model("contenttypes", "ContentType")

    try:
        user_content_type = ContentType.objects.get(app_label="users", model="user")
        user_content_type.app_label = "organizations"
        user_content_type.save()
    except ContentType.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("contenttypes", "__latest__"),
        ("organizations", "0005_alter_organizationmembership_user_and_more"),
    ]

    operations = [
        migrations.RunPython(move_user_model, reverse_move_user_model),
    ]
