# Generated by Django 6.0.1 on 2026-02-26 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
        ('users', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_organization',
            field=models.ForeignKey(blank=True, help_text="The user's default organization (used for login redirect)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='organizations.organization'),
        ),
    ]
