# Generated by Django 6.0.1 on 2026-02-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_move_user_from_organizations'),
        ('users', '0002_user'),
    ]

    operations = [
    ]
