# Generated by Django 6.0.1 on 2026-04-04 06:57

import django.contrib.auth.models
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.ActiveUserManager()),
                ('all_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft-delete timestamp; non-null means the account has been deleted', null=True),
        ),
    ]
